### ISSUE TITLE
同一个帖子反复修改他的悬赏金额,然后反复给最佳回复可以刷钱

### ISSUE THREAD

**Issue by March7online** [zxy19/flarum-answer-bounty#1]
理论上自己的帖子,设置自己为最佳回复,金额应该不变![Screenshot_2024-10-11_04-55-42](https://github.com/user-attachments/assets/6aebd919-c89f-469e-88ec-d2d5ebeaa78b)
**
![image](https://github.com/user-attachments/assets/cb189687-0a85-429e-ba4b-35f286c001fa)

**Comment by zxy19** [comment]
请查看版本V1.0.2并检查是否仍然存在问题。
旧版本忘记限制了，悬赏应该只有在没有设置最佳答案的时候能够更改。感谢反馈

Check version v1.0.2 and test if the problem still present.
A limitation is forgeten that bounty should only be able to edit when there is no best answer.
Thanks for reporting.
