### ISSUE TITLE
新bug来喽

### ISSUE THREAD

**Issue by March7online** [zxy19/flarum-answer-bounty#2]
同一个帖子多次设置最佳回复也能刷钱,我初始只有5,现在变成15了
![image](https://github.com/user-attachments/assets/58645e6c-6d94-4821-852b-9a619585652c)

![image](https://github.com/user-attachments/assets/5f389297-0cb5-4b8b-af55-1b0fb9baf6c8)

**Comment by zxy19** [comment]
请详细描述问题，无法根据该步骤复现。

**Comment by March7online** [comment]
同一个帖子,我设置第一个回复为最佳回复,然后再设置第二个回复为最佳回复,再设置第三个回复为最佳回复,我能拿三次赏金

**Comment by zxy19** [comment]
你是怎么做到不取消答案的情况下设置新的最佳答案的小鱼飘飘

**Comment by March7online** [comment]
> 你是怎么做到不取消答案的情况下设置新的最佳答案的小鱼飘飘

我给你录了个视频https://1drv.ms/v/s!AmxlZW7dAtkZhDK7GsuAkUKd9CdY

**Comment by zxy19** [comment]
了解了，稍晚会进行修复。谢谢反馈小鱼飘飘

**Comment by zxy19** [comment]
v1.0.3修复，感谢反馈
